# Generated by Django 5.1.6 on 2025-03-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='entry',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
