# Generated by Django 5.1.6 on 2025-05-12 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_gallery', to='blog.article'),
        ),
    ]
